//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestAlmacenesJapon.DBEntityFW
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int Id_Empleado { get; set; }
        public string Nombre { get; set; }
        public string DPI { get; set; }
        public short Cantidad_Hijos { get; set; }
        public double Salario_Base { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Bono_Decreto { get; set; }
        public System.DateTime Fecha_Nacimiento { get; set; }
        public string Email { get; set; }
        public string Usuario { get; set; }
        public string Contrasenia { get; set; }
        public string Contrasenia_Salt { get; set; }
    }
}
